name: Data update
on:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: "0 0,6,12,18,20 * * *"

jobs:
  scheduled-data-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
          architecture: 'x64'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
      - name: run update script
        id: update-script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/plotter/rki-age_group-cases-deaths.py
      - name: merge prs
        id: merge-pr
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "PR URL: ${{ steps.update-script.outputs.pr_url }}"
          echo "PR ID: ${{ steps.update-script.outputs.pr_id }}"
          hub api -XPUT "repos/masdot/cdp-corona-data-projects/pulls/${{ steps.update-script.outputs.pr_id }}/merge"
